/* ==========================================================================
   Afya kwa wote — Doctor Appointment Booking
   Vanilla JS: doctor data, search/filter, booking panel,
   localStorage-backed appointments and dashboard.
   ========================================================================== */

const APPT_KEY = "docbook_appointments";

const SPECIALTY_COLORS = {
  Cardiology: { bg: "#ffe1e1", fg: "#b23b3b" },
  Dermatology: { bg: "#f3e5ff", fg: "#7b4fa3" },
  Pediatrics: { bg: "#fff6d9", fg: "#a9790a" },
  Orthopedics: { bg: "#e3edff", fg: "#2c5aa0" },
  Neurology: { bg: "#e9e4ff", fg: "#5b3fae" },
  Dentistry: { bg: "#dcf7ee", fg: "#1f8f6b" },
  "General Medicine": { bg: "#dff0ff", fg: "#2c6298" },
  Gynecology: { bg: "#ffe3ee", fg: "#b23b74" },
};

const DOCTORS = [
  {
    id: "d1",
    name: "Dr. Amara Achieng",
    specialty: "Cardiology",
    hospital: "Nairobi General Hospital",
    location: "Nairobi CBD",
    fee: 3500,
    rating: 4.8,
    reviews: 124,
    availability: "today",
    bio: "Specialist in heart health and preventive cardiac care, focused on clear, calm explanations for every patient.",
  },
  {
    id: "d2",
    name: "Dr. Brian Otieno",
    specialty: "Dermatology",
    hospital: "Riverside Medical Center",
    location: "Westlands",
    fee: 2200,
    rating: 4.6,
    reviews: 89,
    availability: "few",
    bio: "Treats skin, hair, and nail conditions with a gentle, evidence-based approach.",
  },
  {
    id: "d3",
    name: "Dr. Grace Wanjiru",
    specialty: "Pediatrics",
    hospital: "Sunrise Family Clinic",
    location: "Kilimani",
    fee: 1500,
    rating: 4.9,
    reviews: 210,
    availability: "today",
    bio: "Warm, patient-first care for infants through teens, from check-ups to same-day illness visits.",
  },
  {
    id: "d4",
    name: "Dr. Samuel Kiptoo",
    specialty: "Orthopedics",
    hospital: "Lakeview Hospital",
    location: "Karen",
    fee: 3000,
    rating: 4.7,
    reviews: 95,
    availability: "week",
    bio: "Focuses on joint, bone, and sports injury recovery with a practical, movement-first philosophy.",
  },
  {
    id: "d5",
    name: "Dr. Fatima Noor",
    specialty: "Neurology",
    hospital: "St. Mary's Medical Center",
    location: "Parklands",
    fee: 4000,
    rating: 4.9,
    reviews: 67,
    availability: "few",
    bio: "Diagnoses and manages headaches, nerve conditions, and neurological disorders.",
  },
  {
    id: "d6",
    name: "Dr. James Mwangi",
    specialty: "Dentistry",
    hospital: "Bright Smile Dental Clinic",
    location: "Lavington",
    fee: 1800,
    rating: 4.5,
    reviews: 150,
    availability: "today",
    bio: "General and cosmetic dentistry, with a focus on making every visit anxiety-free.",
  },
  {
    id: "d7",
    name: "Dr. Linda Chebet",
    specialty: "General Medicine",
    hospital: "Nairobi General Hospital",
    location: "Nairobi CBD",
    fee: 1000,
    rating: 4.6,
    reviews: 180,
    availability: "today",
    bio: "Your first stop for everyday health concerns, check-ups, and referrals.",
  },
  {
    id: "d8",
    name: "Dr. Peter Njoroge",
    specialty: "Gynecology",
    hospital: "Riverside Medical Center",
    location: "Westlands",
    fee: 2500,
    rating: 4.8,
    reviews: 102,
    availability: "few",
    bio: "Comprehensive women's health care delivered with respect and discretion.",
  },
];

const BASE_SLOTS = [
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
];

const AVAILABILITY_LABELS = {
  today: { text: "Available today", cls: "badge-today" },
  few: { text: "Few slots left", cls: "badge-few" },
  week: { text: "Next available this week", cls: "badge-week" },
};